
package ar.edu.ubp.das.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.6
 * Tue Nov 14 20:55:46 ART 2023
 * Generated source version: 3.5.6
 */

@XmlRootElement(name = "getTiposServicios", namespace = "http://ws.das.ubp.edu.ar/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getTiposServicios", namespace = "http://ws.das.ubp.edu.ar/")

public class GetTiposServicios {


}

